Feature: Submarine
Verifying the submarine controls are correct

    Scenario: Submarine default position
        Then submarine depth should be 0
        And submarine position should be 0
        And submarine aim should be 0

    @excluded
    Scenario: Step 1
        When submarine receives command forward 5
        Then submarine depth should be 0
        And submarine position should be 5
        And submarine aim should be 0

    @excluded
    Scenario: Step 2
        When submarine receives command forward 5
        And submarine receives command down 5
        Then submarine depth should be 0
        And submarine position should be 5
        And submarine aim should be 5

    @excluded
    Scenario: Step 3
        When submarine receives command forward 5
        And submarine receives command down 5
        And submarine receives command forward 8
        Then submarine depth should be 40
        And submarine position should be 13
        And submarine aim should be 5

    @excluded
    Scenario: Step 4
        When submarine receives command forward 5
        And submarine receives command down 5
        And submarine receives command forward 8
        And submarine receives command up 3
        Then submarine depth should be 40
        And submarine position should be 13
        And submarine aim should be 2

    @excluded
    Scenario: Step 5
        When submarine receives command forward 5
        And submarine receives command down 5
        And submarine receives command forward 8
        And submarine receives command up 3
        And submarine receives command down 8
        Then submarine depth should be 40
        And submarine position should be 13
        And submarine aim should be 10

    @excluded
    Scenario: Step 6
        When submarine receives command forward 5
        And submarine receives command down 5
        And submarine receives command forward 8
        And submarine receives command up 3
        And submarine receives command down 8
        And submarine receives command forward 2
        Then submarine depth should be 60
        And submarine position should be 15
        And submarine aim should be 10
        And submarine final value should be 900

    @excluded
    Scenario: Full features
        When submarine receives command forward 1
        And submarine receives command forward 8
        And submarine receives command down 9
        And submarine receives command forward 3
        And submarine receives command down 6
        And submarine receives command down 1
        And submarine receives command down 1
        And submarine receives command forward 5
        And submarine receives command forward 5
        And submarine receives command forward 8
        And submarine receives command down 6
        And submarine receives command forward 7
        And submarine receives command down 3
        And submarine receives command down 4
        And submarine receives command up 1
        And submarine receives command forward 7
        And submarine receives command forward 5
        And submarine receives command forward 8
        And submarine receives command down 1
        And submarine receives command forward 9
        And submarine receives command forward 9
        And submarine receives command forward 7
        And submarine receives command up 8
        And submarine receives command forward 5
        And submarine receives command forward 9
        And submarine receives command down 3
        And submarine receives command forward 2
        And submarine receives command down 5
        And submarine receives command down 4
        And submarine receives command up 2
        And submarine receives command up 5
        And submarine receives command forward 3
        And submarine receives command forward 8
        And submarine receives command down 9
        And submarine receives command down 1
        And submarine receives command forward 2
        And submarine receives command forward 6
        And submarine receives command up 2
        And submarine receives command up 9
        And submarine receives command forward 8
        And submarine receives command down 7
        And submarine receives command forward 2
        And submarine receives command up 5
        And submarine receives command forward 7
        And submarine receives command down 9
        And submarine receives command forward 9
        And submarine receives command forward 5
        And submarine receives command down 8
        And submarine receives command down 6
        And submarine receives command forward 2
        And submarine receives command up 4
        And submarine receives command down 2
        And submarine receives command down 9
        And submarine receives command forward 4
        And submarine receives command down 4
        And submarine receives command forward 9
        And submarine receives command down 8
        And submarine receives command down 7
        And submarine receives command down 4
        And submarine receives command forward 6
        And submarine receives command forward 9
        And submarine receives command up 7
        And submarine receives command down 2
        And submarine receives command up 6
        And submarine receives command down 8
        And submarine receives command forward 3
        And submarine receives command forward 9
        And submarine receives command forward 7
        And submarine receives command down 1
        And submarine receives command forward 1
        And submarine receives command forward 7
        And submarine receives command forward 5
        And submarine receives command down 4
        And submarine receives command down 1
        And submarine receives command forward 4
        And submarine receives command forward 9
        And submarine receives command forward 6
        And submarine receives command down 5
        And submarine receives command down 1
        And submarine receives command forward 9
        And submarine receives command down 6
        And submarine receives command down 4
        And submarine receives command forward 8
        And submarine receives command up 8
        And submarine receives command forward 9
        And submarine receives command up 9
        And submarine receives command up 9
        And submarine receives command up 7
        And submarine receives command forward 4
        And submarine receives command down 4
        And submarine receives command forward 4
        And submarine receives command forward 2
        And submarine receives command forward 2
        And submarine receives command forward 9
        And submarine receives command up 4
        And submarine receives command forward 4
        And submarine receives command forward 3
        And submarine receives command forward 5
        And submarine receives command down 3
        And submarine receives command up 4
        And submarine receives command forward 3
        And submarine receives command forward 5
        And submarine receives command forward 9
        And submarine receives command forward 7
        And submarine receives command down 1
        And submarine receives command forward 4
        And submarine receives command down 5
        And submarine receives command up 6
        And submarine receives command down 9
        And submarine receives command forward 8
        And submarine receives command down 1
        And submarine receives command forward 3
        And submarine receives command down 2
        And submarine receives command up 8
        And submarine receives command down 5
        And submarine receives command down 8
        And submarine receives command forward 5
        And submarine receives command down 6
        And submarine receives command forward 6
        And submarine receives command down 7
        And submarine receives command up 5
        And submarine receives command forward 8
        And submarine receives command forward 5
        And submarine receives command forward 7
        And submarine receives command up 3
        And submarine receives command down 6
        And submarine receives command up 9
        And submarine receives command forward 1
        And submarine receives command forward 7
        And submarine receives command forward 3
        And submarine receives command forward 8
        And submarine receives command up 4
        And submarine receives command up 9
        And submarine receives command down 5
        And submarine receives command forward 5
        And submarine receives command forward 4
        And submarine receives command forward 4
        And submarine receives command down 9
        And submarine receives command up 6
        And submarine receives command forward 5
        And submarine receives command forward 2
        And submarine receives command down 6
        And submarine receives command down 2
        And submarine receives command forward 9
        And submarine receives command down 7
        And submarine receives command forward 8
        And submarine receives command down 4
        And submarine receives command forward 8
        And submarine receives command forward 8
        And submarine receives command up 7
        And submarine receives command up 5
        And submarine receives command forward 6
        And submarine receives command forward 4
        And submarine receives command up 4
        And submarine receives command forward 2
        And submarine receives command up 3
        And submarine receives command down 8
        And submarine receives command forward 1
        And submarine receives command forward 8
        And submarine receives command forward 8
        And submarine receives command forward 4
        And submarine receives command up 7
        And submarine receives command forward 2
        And submarine receives command down 8
        And submarine receives command forward 1
        And submarine receives command down 1
        And submarine receives command down 4
        And submarine receives command up 3
        And submarine receives command forward 8
        And submarine receives command forward 1
        And submarine receives command down 9
        And submarine receives command up 5
        And submarine receives command down 5
        And submarine receives command forward 9
        And submarine receives command forward 4
        And submarine receives command up 7
        And submarine receives command down 2
        And submarine receives command down 4
        And submarine receives command forward 1
        And submarine receives command forward 6
        And submarine receives command up 8
        And submarine receives command up 1
        And submarine receives command forward 8
        And submarine receives command down 5
        And submarine receives command down 5
        And submarine receives command forward 9
        And submarine receives command down 8
        And submarine receives command forward 9
        And submarine receives command down 1
        And submarine receives command up 7
        And submarine receives command forward 8
        And submarine receives command up 2
        And submarine receives command down 2
        And submarine receives command up 1
        And submarine receives command up 9
        And submarine receives command forward 6
        And submarine receives command down 5
        And submarine receives command forward 1
        And submarine receives command down 2
        And submarine receives command forward 5
        And submarine receives command down 3
        And submarine receives command up 8
        And submarine receives command down 2
        And submarine receives command down 8
        And submarine receives command forward 7
        And submarine receives command forward 2
        And submarine receives command up 3
        And submarine receives command forward 3
        And submarine receives command down 1
        And submarine receives command forward 4
        And submarine receives command down 7
        And submarine receives command up 5
        And submarine receives command forward 8
        And submarine receives command forward 8
        And submarine receives command up 6
        And submarine receives command up 4
        And submarine receives command up 4
        And submarine receives command down 7
        And submarine receives command forward 2
        And submarine receives command forward 1
        And submarine receives command forward 6
        And submarine receives command up 3
        And submarine receives command forward 3
        And submarine receives command forward 9
        And submarine receives command down 4
        And submarine receives command forward 2
        And submarine receives command down 9
        And submarine receives command down 8
        And submarine receives command forward 5
        And submarine receives command forward 2
        And submarine receives command forward 4
        And submarine receives command forward 5
        And submarine receives command forward 7
        And submarine receives command down 4
        And submarine receives command up 5
        And submarine receives command down 7
        And submarine receives command forward 4
        And submarine receives command up 7
        And submarine receives command down 9
        And submarine receives command down 4
        And submarine receives command down 3
        And submarine receives command forward 8
        And submarine receives command down 5
        And submarine receives command forward 8
        And submarine receives command forward 8
        And submarine receives command down 3
        And submarine receives command down 8
        And submarine receives command down 2
        And submarine receives command forward 4
        And submarine receives command forward 5
        And submarine receives command down 7
        And submarine receives command down 7
        And submarine receives command down 6
        And submarine receives command up 9
        And submarine receives command down 9
        And submarine receives command down 5
        And submarine receives command forward 4
        And submarine receives command down 1
        And submarine receives command down 7
        And submarine receives command up 4
        And submarine receives command down 8
        And submarine receives command up 5
        And submarine receives command up 1
        And submarine receives command down 9
        And submarine receives command down 7
        And submarine receives command forward 9
        And submarine receives command forward 7
        And submarine receives command down 6
        And submarine receives command up 2
        And submarine receives command forward 1
        And submarine receives command down 8
        And submarine receives command up 2
        And submarine receives command forward 8
        And submarine receives command down 2
        And submarine receives command forward 2
        And submarine receives command down 9
        And submarine receives command forward 2
        And submarine receives command forward 3
        And submarine receives command forward 7
        And submarine receives command up 3
        And submarine receives command up 3
        And submarine receives command up 3
        And submarine receives command forward 5
        And submarine receives command up 9
        And submarine receives command up 1
        And submarine receives command down 9
        And submarine receives command down 4
        And submarine receives command down 5
        And submarine receives command up 9
        And submarine receives command up 7
        And submarine receives command down 9
        And submarine receives command forward 3
        And submarine receives command down 5
        And submarine receives command down 6
        And submarine receives command down 3
        And submarine receives command up 6
        And submarine receives command forward 8
        And submarine receives command up 6
        And submarine receives command up 8
        And submarine receives command down 4
        And submarine receives command forward 8
        And submarine receives command down 8
        And submarine receives command forward 7
        And submarine receives command up 1
        And submarine receives command forward 4
        And submarine receives command down 2
        And submarine receives command forward 7
        And submarine receives command down 6
        And submarine receives command up 8
        And submarine receives command forward 1
        And submarine receives command down 8
        And submarine receives command down 4
        And submarine receives command forward 7
        And submarine receives command forward 2
        And submarine receives command up 4
        And submarine receives command forward 9
        And submarine receives command forward 9
        And submarine receives command down 8
        And submarine receives command up 1
        And submarine receives command down 3
        And submarine receives command forward 7
        And submarine receives command down 9
        And submarine receives command forward 2
        And submarine receives command forward 5
        And submarine receives command down 4
        And submarine receives command down 8
        And submarine receives command down 3
        And submarine receives command up 1
        And submarine receives command down 2
        And submarine receives command up 3
        And submarine receives command forward 1
        And submarine receives command forward 5
        And submarine receives command forward 3
        And submarine receives command down 2
        And submarine receives command up 2
        And submarine receives command forward 7
        And submarine receives command down 6
        And submarine receives command forward 3
        And submarine receives command down 8
        And submarine receives command forward 5
        And submarine receives command forward 4
        And submarine receives command up 2
        And submarine receives command forward 4
        And submarine receives command up 2
        And submarine receives command down 4
        And submarine receives command forward 8
        And submarine receives command forward 5
        And submarine receives command down 1
        And submarine receives command forward 6
        And submarine receives command down 2
        And submarine receives command down 5
        And submarine receives command up 8
        And submarine receives command forward 5
        And submarine receives command down 2
        And submarine receives command up 5
        And submarine receives command down 5
        And submarine receives command forward 4
        And submarine receives command forward 3
        And submarine receives command forward 8
        And submarine receives command down 9
        And submarine receives command up 3
        And submarine receives command forward 4
        And submarine receives command forward 2
        And submarine receives command forward 2
        And submarine receives command forward 2
        And submarine receives command down 4
        And submarine receives command forward 8
        And submarine receives command forward 5
        And submarine receives command up 3
        And submarine receives command down 1
        And submarine receives command forward 3
        And submarine receives command up 5
        And submarine receives command forward 8
        And submarine receives command down 6
        And submarine receives command forward 6
        And submarine receives command down 9
        And submarine receives command forward 6
        And submarine receives command up 5
        And submarine receives command down 6
        And submarine receives command up 9
        And submarine receives command forward 8
        And submarine receives command down 2
        And submarine receives command forward 9
        And submarine receives command down 7
        And submarine receives command down 5
        And submarine receives command down 4
        And submarine receives command forward 3
        And submarine receives command forward 2
        And submarine receives command forward 1
        And submarine receives command forward 7
        And submarine receives command down 3
        And submarine receives command forward 4
        And submarine receives command up 6
        And submarine receives command down 5
        And submarine receives command down 4
        And submarine receives command down 8
        And submarine receives command down 4
        And submarine receives command up 6
        And submarine receives command forward 3
        And submarine receives command down 4
        And submarine receives command down 6
        And submarine receives command forward 9
        And submarine receives command forward 6
        And submarine receives command up 4
        And submarine receives command down 2
        And submarine receives command down 7
        And submarine receives command forward 2
        And submarine receives command forward 9
        And submarine receives command down 4
        And submarine receives command down 8
        And submarine receives command down 3
        And submarine receives command down 4
        And submarine receives command forward 9
        And submarine receives command forward 4
        And submarine receives command forward 1
        And submarine receives command down 7
        And submarine receives command forward 2
        And submarine receives command up 1
        And submarine receives command forward 7
        And submarine receives command down 7
        And submarine receives command forward 7
        And submarine receives command forward 5
        And submarine receives command up 8
        And submarine receives command down 4
        And submarine receives command up 7
        And submarine receives command up 2
        And submarine receives command up 7
        And submarine receives command up 8
        And submarine receives command down 9
        And submarine receives command forward 8
        And submarine receives command forward 8
        And submarine receives command down 3
        And submarine receives command forward 9
        And submarine receives command down 3
        And submarine receives command up 7
        And submarine receives command down 1
        And submarine receives command down 9
        And submarine receives command forward 2
        And submarine receives command up 4
        And submarine receives command down 2
        And submarine receives command forward 2
        And submarine receives command up 5
        And submarine receives command up 5
        And submarine receives command up 1
        And submarine receives command forward 7
        And submarine receives command up 5
        And submarine receives command down 3
        And submarine receives command up 8
        And submarine receives command down 9
        And submarine receives command down 7
        And submarine receives command up 4
        And submarine receives command down 8
        And submarine receives command down 4
        And submarine receives command forward 8
        And submarine receives command up 6
        And submarine receives command down 2
        And submarine receives command down 4
        And submarine receives command forward 7
        And submarine receives command forward 8
        And submarine receives command forward 8
        And submarine receives command forward 1
        And submarine receives command down 4
        And submarine receives command down 4
        And submarine receives command forward 4
        And submarine receives command down 7
        And submarine receives command forward 3
        And submarine receives command down 3
        And submarine receives command down 6
        And submarine receives command down 7
        And submarine receives command down 6
        And submarine receives command forward 8
        And submarine receives command down 4
        And submarine receives command down 7
        And submarine receives command down 1
        And submarine receives command down 7
        And submarine receives command down 5
        And submarine receives command down 2
        And submarine receives command up 5
        And submarine receives command forward 9
        And submarine receives command down 3
        And submarine receives command down 4
        And submarine receives command down 4
        And submarine receives command forward 5
        And submarine receives command down 9
        And submarine receives command forward 1
        And submarine receives command up 1
        And submarine receives command up 1
        And submarine receives command down 3
        And submarine receives command forward 8
        And submarine receives command up 6
        And submarine receives command up 6
        And submarine receives command down 1
        And submarine receives command up 2
        And submarine receives command down 7
        And submarine receives command down 9
        And submarine receives command up 7
        And submarine receives command forward 7
        And submarine receives command down 6
        And submarine receives command down 5
        And submarine receives command down 5
        And submarine receives command up 8
        And submarine receives command forward 7
        And submarine receives command down 1
        And submarine receives command down 6
        And submarine receives command forward 4
        And submarine receives command forward 5
        And submarine receives command forward 5
        And submarine receives command forward 2
        And submarine receives command down 5
        And submarine receives command up 6
        And submarine receives command down 5
        And submarine receives command forward 1
        And submarine receives command down 9
        And submarine receives command up 4
        And submarine receives command down 7
        And submarine receives command down 8
        And submarine receives command down 5
        And submarine receives command down 8
        And submarine receives command forward 7
        And submarine receives command forward 2
        And submarine receives command up 3
        And submarine receives command down 7
        And submarine receives command forward 1
        And submarine receives command forward 4
        And submarine receives command forward 5
        And submarine receives command forward 1
        And submarine receives command forward 7
        And submarine receives command down 6
        And submarine receives command forward 9
        And submarine receives command forward 8
        And submarine receives command down 5
        And submarine receives command forward 5
        And submarine receives command forward 8
        And submarine receives command forward 3
        And submarine receives command up 1
        And submarine receives command forward 6
        And submarine receives command forward 9
        And submarine receives command forward 8
        And submarine receives command down 3
        And submarine receives command forward 8
        And submarine receives command forward 7
        And submarine receives command down 1
        And submarine receives command forward 9
        And submarine receives command down 9
        And submarine receives command forward 6
        And submarine receives command forward 4
        And submarine receives command forward 2
        And submarine receives command forward 9
        And submarine receives command down 7
        And submarine receives command down 6
        And submarine receives command forward 4
        And submarine receives command forward 1
        And submarine receives command forward 3
        And submarine receives command forward 9
        And submarine receives command up 4
        And submarine receives command down 5
        And submarine receives command forward 6
        And submarine receives command down 8
        And submarine receives command up 5
        And submarine receives command down 9
        And submarine receives command down 6
        And submarine receives command forward 7
        And submarine receives command down 9
        And submarine receives command forward 6
        And submarine receives command forward 5
        And submarine receives command down 1
        And submarine receives command down 4
        And submarine receives command up 6
        And submarine receives command forward 2
        And submarine receives command down 8
        And submarine receives command down 5
        And submarine receives command up 5
        And submarine receives command forward 6
        And submarine receives command forward 5
        And submarine receives command down 8
        And submarine receives command down 4
        And submarine receives command down 3
        And submarine receives command down 8
        And submarine receives command forward 3
        And submarine receives command forward 9
        And submarine receives command up 6
        And submarine receives command down 9
        And submarine receives command down 1
        And submarine receives command forward 7
        And submarine receives command forward 5
        And submarine receives command down 5
        And submarine receives command down 1
        And submarine receives command forward 7
        And submarine receives command forward 3
        And submarine receives command up 6
        And submarine receives command forward 1
        And submarine receives command up 9
        And submarine receives command forward 1
        And submarine receives command down 4
        And submarine receives command down 3
        And submarine receives command down 3
        And submarine receives command up 6
        And submarine receives command forward 9
        And submarine receives command forward 5
        And submarine receives command up 9
        And submarine receives command up 5
        And submarine receives command forward 5
        And submarine receives command forward 7
        And submarine receives command forward 9
        And submarine receives command down 8
        And submarine receives command forward 2
        And submarine receives command down 7
        And submarine receives command down 7
        And submarine receives command forward 3
        And submarine receives command down 2
        And submarine receives command up 1
        And submarine receives command down 4
        And submarine receives command down 6
        And submarine receives command down 8
        And submarine receives command forward 8
        And submarine receives command forward 6
        And submarine receives command up 3
        And submarine receives command forward 9
        And submarine receives command down 8
        And submarine receives command up 7
        And submarine receives command forward 6
        And submarine receives command forward 9
        And submarine receives command up 8
        And submarine receives command forward 3
        And submarine receives command down 9
        And submarine receives command forward 3
        And submarine receives command forward 4
        And submarine receives command down 3
        And submarine receives command down 2
        And submarine receives command forward 2
        And submarine receives command down 5
        And submarine receives command down 9
        And submarine receives command down 2
        And submarine receives command down 7
        And submarine receives command down 4
        And submarine receives command down 6
        And submarine receives command forward 5
        And submarine receives command up 1
        And submarine receives command forward 9
        And submarine receives command forward 2
        And submarine receives command up 8
        And submarine receives command forward 8
        And submarine receives command down 3
        And submarine receives command forward 7
        And submarine receives command down 5
        And submarine receives command forward 5
        And submarine receives command down 5
        And submarine receives command down 9
        And submarine receives command down 9
        And submarine receives command down 6
        And submarine receives command down 5
        And submarine receives command down 4
        And submarine receives command up 6
        And submarine receives command forward 9
        And submarine receives command down 2
        And submarine receives command down 5
        And submarine receives command up 3
        And submarine receives command forward 8
        And submarine receives command forward 1
        And submarine receives command down 4
        And submarine receives command down 8
        And submarine receives command forward 6
        And submarine receives command forward 7
        And submarine receives command up 2
        And submarine receives command forward 1
        And submarine receives command forward 2
        And submarine receives command down 7
        And submarine receives command down 6
        And submarine receives command up 7
        And submarine receives command forward 7
        And submarine receives command down 6
        And submarine receives command down 6
        And submarine receives command down 8
        And submarine receives command forward 8
        And submarine receives command up 5
        And submarine receives command up 9
        And submarine receives command forward 8
        And submarine receives command forward 1
        And submarine receives command down 6
        And submarine receives command down 6
        And submarine receives command up 7
        And submarine receives command forward 6
        And submarine receives command up 5
        And submarine receives command forward 7
        And submarine receives command down 1
        And submarine receives command forward 1
        And submarine receives command forward 9
        And submarine receives command up 7
        And submarine receives command down 3
        And submarine receives command forward 4
        And submarine receives command down 6
        And submarine receives command down 6
        And submarine receives command up 5
        And submarine receives command up 7
        And submarine receives command down 1
        And submarine receives command up 2
        And submarine receives command down 8
        And submarine receives command down 1
        And submarine receives command forward 2
        And submarine receives command down 3
        And submarine receives command forward 8
        And submarine receives command forward 2
        And submarine receives command up 2
        And submarine receives command down 7
        And submarine receives command forward 5
        And submarine receives command forward 7
        And submarine receives command down 2
        And submarine receives command up 1
        And submarine receives command down 1
        And submarine receives command down 6
        And submarine receives command down 4
        And submarine receives command up 1
        And submarine receives command forward 2
        And submarine receives command forward 7
        And submarine receives command forward 8
        And submarine receives command down 1
        And submarine receives command forward 6
        And submarine receives command down 5
        And submarine receives command down 8
        And submarine receives command up 6
        And submarine receives command down 7
        And submarine receives command forward 6
        And submarine receives command down 8
        And submarine receives command down 6
        And submarine receives command down 9
        And submarine receives command forward 8
        And submarine receives command down 9
        And submarine receives command down 6
        And submarine receives command up 2
        And submarine receives command down 2
        And submarine receives command down 5
        And submarine receives command down 5
        And submarine receives command up 8
        And submarine receives command forward 6
        And submarine receives command forward 7
        And submarine receives command up 4
        And submarine receives command down 5
        And submarine receives command up 5
        And submarine receives command forward 6
        And submarine receives command forward 8
        And submarine receives command up 6
        And submarine receives command up 7
        And submarine receives command up 3
        And submarine receives command up 9
        And submarine receives command down 6
        And submarine receives command forward 3
        And submarine receives command forward 3
        And submarine receives command down 6
        And submarine receives command down 8
        And submarine receives command down 2
        And submarine receives command down 2
        And submarine receives command up 7
        And submarine receives command up 6
        And submarine receives command forward 5
        And submarine receives command forward 4
        And submarine receives command down 2
        And submarine receives command down 3
        And submarine receives command forward 8
        And submarine receives command down 9
        And submarine receives command forward 3
        And submarine receives command down 8
        And submarine receives command down 8
        And submarine receives command forward 9
        And submarine receives command forward 7
        And submarine receives command down 8
        And submarine receives command down 7
        And submarine receives command up 2
        And submarine receives command down 8
        And submarine receives command down 1
        And submarine receives command down 7
        And submarine receives command up 7
        And submarine receives command forward 3
        And submarine receives command forward 5
        And submarine receives command up 1
        And submarine receives command down 9
        And submarine receives command forward 3
        And submarine receives command down 4
        And submarine receives command down 5
        And submarine receives command down 3
        And submarine receives command down 8
        And submarine receives command up 7
        And submarine receives command forward 4
        And submarine receives command down 6
        And submarine receives command forward 9
        And submarine receives command forward 9
        And submarine receives command forward 1
        And submarine receives command up 6
        And submarine receives command up 8
        And submarine receives command forward 6
        And submarine receives command down 6
        And submarine receives command down 6
        And submarine receives command forward 1
        And submarine receives command up 4
        And submarine receives command down 2
        And submarine receives command forward 8
        And submarine receives command forward 6
        And submarine receives command down 2
        And submarine receives command down 9
        And submarine receives command down 6
        And submarine receives command down 4
        And submarine receives command forward 5
        And submarine receives command down 5
        And submarine receives command down 7
        And submarine receives command down 6
        And submarine receives command forward 8
        And submarine receives command down 8
        And submarine receives command down 2
        And submarine receives command up 2
        And submarine receives command up 2
        And submarine receives command down 3
        And submarine receives command forward 2
        And submarine receives command down 2
        And submarine receives command down 5
        And submarine receives command down 3
        And submarine receives command up 5
        And submarine receives command down 8
        And submarine receives command forward 8
        And submarine receives command down 8
        And submarine receives command down 4
        And submarine receives command down 3
        And submarine receives command forward 7
        And submarine receives command forward 1
        And submarine receives command forward 1
        And submarine receives command down 7
        And submarine receives command down 6
        And submarine receives command down 2
        And submarine receives command up 9
        And submarine receives command up 7
        And submarine receives command down 9
        And submarine receives command forward 1
        And submarine receives command down 3
        And submarine receives command down 4
        And submarine receives command down 7
        And submarine receives command forward 6
        And submarine receives command down 8
        And submarine receives command forward 3
        And submarine receives command down 6
        And submarine receives command forward 4
        And submarine receives command down 3
        And submarine receives command down 5
        And submarine receives command down 4
        And submarine receives command forward 4
        And submarine receives command up 4
        And submarine receives command up 1
        And submarine receives command up 2
        And submarine receives command down 3
        And submarine receives command forward 6
        And submarine receives command up 6
        And submarine receives command forward 8
        And submarine receives command forward 9
        And submarine receives command forward 3
        And submarine receives command forward 4
        And submarine receives command forward 2
        And submarine receives command forward 8
        And submarine receives command forward 7
        And submarine receives command up 4
        And submarine receives command down 5
        And submarine receives command forward 8
        And submarine receives command forward 6
        And submarine receives command down 2
        And submarine receives command forward 3
        And submarine receives command down 5
        And submarine receives command down 8
        And submarine receives command forward 3
        And submarine receives command forward 4
        And submarine receives command down 3
        And submarine receives command down 9
        And submarine receives command down 6
        And submarine receives command up 6
        And submarine receives command down 1
        And submarine receives command down 8
        And submarine receives command forward 7
        And submarine receives command down 3
        And submarine receives command forward 8
        And submarine receives command forward 4
        And submarine receives command down 2
        And submarine receives command up 7
        And submarine receives command down 5
        And submarine receives command forward 1
        And submarine receives command forward 7
        And submarine receives command forward 1
        And submarine receives command forward 3
        And submarine receives command down 8
        And submarine receives command down 7
        And submarine receives command forward 5
        And submarine receives command forward 3
        And submarine receives command down 1
        And submarine receives command forward 7
        And submarine receives command down 4
        And submarine receives command down 3
        And submarine receives command down 6
        And submarine receives command down 9
        And submarine receives command forward 6
        And submarine receives command down 1
        And submarine receives command forward 3
        And submarine receives command forward 3
        And submarine receives command forward 5
        And submarine receives command forward 9
        And submarine receives command up 3
        And submarine receives command up 6
        And submarine receives command forward 7
        And submarine receives command up 5
        And submarine receives command up 9
        And submarine receives command down 2
        And submarine receives command down 5
        And submarine receives command up 5
        And submarine receives command forward 4
        And submarine receives command forward 4
        And submarine receives command forward 6
        And submarine receives command up 2
        And submarine receives command down 9
        And submarine receives command down 4
        And submarine receives command down 2
        And submarine receives command forward 7
        And submarine receives command down 3
        And submarine receives command up 4
        And submarine receives command up 6
        And submarine receives command forward 7
        And submarine receives command forward 1
        And submarine receives command forward 1
        And submarine receives command down 7
        And submarine receives command forward 5
        And submarine receives command forward 4
        And submarine receives command up 6
        And submarine receives command forward 4
        And submarine receives command forward 2
        And submarine receives command forward 6
        And submarine receives command up 1
        And submarine receives command up 5
        And submarine receives command forward 8
        And submarine receives command up 2
        And submarine receives command forward 3
        And submarine receives command forward 5
        And submarine receives command up 9
        And submarine receives command down 4
        And submarine receives command forward 1
        And submarine receives command up 7
        And submarine receives command down 5
        And submarine receives command forward 7
        And submarine receives command forward 2
        And submarine receives command forward 8
        And submarine receives command down 8
        And submarine receives command down 2
        And submarine receives command forward 2
        And submarine receives command forward 4
        And submarine receives command forward 8
        And submarine receives command forward 1
        And submarine receives command forward 8
        And submarine receives command forward 2
        And submarine receives command down 9
        And submarine receives command forward 7
        And submarine receives command down 7
        And submarine receives command down 5
        And submarine receives command up 9
        And submarine receives command forward 5
        And submarine receives command down 1
        And submarine receives command down 9
        And submarine receives command down 2
        And submarine receives command forward 6
        And submarine receives command down 8
        And submarine receives command up 9
        And submarine receives command forward 5
        And submarine receives command down 2
        And submarine receives command forward 1
        And submarine receives command up 4
        And submarine receives command forward 1
        And submarine receives command down 9
        And submarine receives command up 3
        And submarine receives command down 3
        And submarine receives command down 2
        And submarine receives command forward 9
        And submarine receives command down 5
        And submarine receives command forward 4
        And submarine receives command down 1
        And submarine receives command forward 4
        And submarine receives command down 8
        And submarine receives command down 3
        And submarine receives command forward 8
        And submarine receives command forward 2
        And submarine receives command forward 3
        And submarine receives command down 1
        And submarine receives command forward 1
        And submarine receives command down 2
        And submarine receives command forward 6
        And submarine receives command up 3
        And submarine receives command up 5
        And submarine receives command up 9
        And submarine receives command forward 9
        And submarine receives command down 5
        And submarine receives command down 5
        And submarine receives command forward 4
        And submarine receives command up 6
        And submarine receives command down 7
        And submarine receives command down 2
        And submarine receives command forward 8
        And submarine receives command forward 6
        And submarine receives command forward 6
        And submarine receives command up 6
        And submarine receives command down 7
        And submarine receives command forward 8
        Then submarine final value should be 2134882034